name: Eventurely
description: "Personal event management to bring people together."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.10
  grpc: ^3.2.4
  riverpod_annotation: ^2.3.4
  protobuf: ^3.1.0
  google_fonts: ^4.0.4
  font_awesome_flutter: ^10.7.0
  flutter_launcher_icons: ^0.13.1
  fixnum: ^1.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_generator: ^2.3.11
  build_runner: ^2.4.8
  custom_lint: ^0.6.0
  riverpod_lint: ^2.3.9

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/eventurely_icon_v0.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/eventurely_icon_v0.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icon/eventurely_icon_v0.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/eventurely_icon_v0.png"
